### ISSUE TITLE
result

### ISSUE THREAD

**Issue by kingmkm** [tuanphan09/captcha-recognition#1]
Thank you for your work. i just wanted to ask what was the result of your testing. Also, i wanted to ask you why is your model different from qjadud1994(CRNN-Keras) and from the CRNN paper.

**Comment by tuanphan09** [comment]
I created my own captcha image using ImageCaptcha and held a small competition base on that data, you can visit the competition via:
https://www.kaggle.com/c/aif-challenge2/ 

I'm the host so I didn't submit my result on that competition. If i were, the result would be:
- Publict test: 91.25%
- Private test: 78.66%

**Comment by tuanphan09** [comment]
About the model, i don't see any big difference between my model and qjadud1994. Both have the same parts as the model from the original paper: CNN -> RNN(stack bi-LSTM) -> CTC loss
